all:
  metas:
    robots: noindex, nofollow
    title: Контакты | Киевская судоходная компания &laquo;Рентфлот&raquo;
  stylesheets: [-*, backend/common.css, backend/screen.css: { position: last }]
  layout:     layout_backend