<?php

/**
 * BaseItemUnitType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $doc_name
 * @property Doctrine_Collection $Items
 * 
 * @method string              getName()     Returns the current record's "name" value
 * @method string              getDocName()  Returns the current record's "doc_name" value
 * @method Doctrine_Collection getItems()    Returns the current record's "Items" collection
 * @method ItemUnitType        setName()     Sets the current record's "name" value
 * @method ItemUnitType        setDocName()  Sets the current record's "doc_name" value
 * @method ItemUnitType        setItems()    Sets the current record's "Items" collection
 * 
 * @package    Rentflot
 * @subpackage model
 * @author     Infosoft
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseItemUnitType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('item_unit_type');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('doc_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Item as Items', array(
             'local' => 'id',
             'foreign' => 'unit_type_id'));
    }
}