<?php

/**
 * BasePayment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $order_id
 * @property double $amount_uah
 * @property Order $Order
 * 
 * @method integer getOrderId()    Returns the current record's "order_id" value
 * @method double  getAmountUah()  Returns the current record's "amount_uah" value
 * @method Order   getOrder()      Returns the current record's "Order" value
 * @method Payment setOrderId()    Sets the current record's "order_id" value
 * @method Payment setAmountUah()  Sets the current record's "amount_uah" value
 * @method Payment setOrder()      Sets the current record's "Order" value
 * 
 * @package    Rentflot
 * @subpackage model
 * @author     Infosoft
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePayment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('payment');
        $this->hasColumn('order_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('amount_uah', 'double', null, array(
             'type' => 'double',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Order', array(
             'local' => 'order_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}