<?php

/**
 * BaseCallback
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $phone
 * 
 * @method string   getPhone() Returns the current record's "phone" value
 * @method Callback setPhone() Sets the current record's "phone" value
 * 
 * @package    Rentflot
 * @subpackage model
 * @author     Infosoft
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCallback extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('callback');
        $this->hasColumn('phone', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}