<?php

/**
 * BaseClient
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $org_name
 * @property string $name
 * @property string $address
 * @property string $phones
 * @property string $email
 * @property string $additional_information
 * @property Doctrine_Collection $Orders
 * 
 * @method string              getOrgName()                Returns the current record's "org_name" value
 * @method string              getName()                   Returns the current record's "name" value
 * @method string              getAddress()                Returns the current record's "address" value
 * @method string              getPhones()                 Returns the current record's "phones" value
 * @method string              getEmail()                  Returns the current record's "email" value
 * @method string              getAdditionalInformation()  Returns the current record's "additional_information" value
 * @method Doctrine_Collection getOrders()                 Returns the current record's "Orders" collection
 * @method Client              setOrgName()                Sets the current record's "org_name" value
 * @method Client              setName()                   Sets the current record's "name" value
 * @method Client              setAddress()                Sets the current record's "address" value
 * @method Client              setPhones()                 Sets the current record's "phones" value
 * @method Client              setEmail()                  Sets the current record's "email" value
 * @method Client              setAdditionalInformation()  Sets the current record's "additional_information" value
 * @method Client              setOrders()                 Sets the current record's "Orders" collection
 * 
 * @package    Rentflot
 * @subpackage model
 * @author     Infosoft
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClient extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('client');
        $this->hasColumn('org_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('address', 'string', 5000, array(
             'type' => 'string',
             'length' => 5000,
             ));
        $this->hasColumn('phones', 'string', 5000, array(
             'type' => 'string',
             'length' => 5000,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('additional_information', 'string', 5000, array(
             'type' => 'string',
             'length' => 5000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Order as Orders', array(
             'local' => 'id',
             'foreign' => 'client_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}