<?php

/**
 * BaseItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property boolean $is_active
 * @property boolean $is_own
 * @property boolean $hide_attractions
 * @property string $name
 * @property string $title
 * @property string $html_description
 * @property string $html_keywords
 * @property string $main_image_title
 * @property string $main_image_alt
 * @property string $listing_text
 * @property string $h1
 * @property string $internal_name
 * @property string $doc_name
 * @property string $slug
 * @property integer $owner_id
 * @property integer $unit_type_id
 * @property double $price_uah
 * @property double $price_discount_uah
 * @property double $commission_percent
 * @property string $short_description
 * @property string $description
 * @property string $target_use
 * @property string $passenger_capacity
 * @property string $basic_info
 * @property string $equipment
 * @property string $crew
 * @property string $passenger_insurance
 * @property string $price
 * @property string $additional_info
 * @property string $in_sight
 * @property string $catering
 * @property string $info_value1
 * @property string $info_text1
 * @property string $info_value2
 * @property string $info_text2
 * @property string $info_value3
 * @property string $info_text3
 * @property string $price_value1
 * @property string $price_text1
 * @property string $price_value2
 * @property string $price_text2
 * @property string $price_value3
 * @property string $price_text3
 * @property integer $main_image_id
 * @property integer $order
 * @property Owner $Owner
 * @property ItemUnitType $UnitType
 * @property ItemImage $MainImage
 * @property Doctrine_Collection $Images
 * @property Doctrine_Collection $Categories
 * @property Doctrine_Collection $ItemCategories
 * @property Doctrine_Collection $Orders
 * @property Doctrine_Collection $ItemOrders
 * 
 * @method boolean             getIsActive()            Returns the current record's "is_active" value
 * @method boolean             getIsOwn()               Returns the current record's "is_own" value
 * @method boolean             getHideAttractions()     Returns the current record's "hide_attractions" value
 * @method string              getName()                Returns the current record's "name" value
 * @method string              getTitle()               Returns the current record's "title" value
 * @method string              getHtmlDescription()     Returns the current record's "html_description" value
 * @method string              getHtmlKeywords()        Returns the current record's "html_keywords" value
 * @method string              getMainImageTitle()      Returns the current record's "main_image_title" value
 * @method string              getMainImageAlt()        Returns the current record's "main_image_alt" value
 * @method string              getListingText()         Returns the current record's "listing_text" value
 * @method string              getH1()                  Returns the current record's "h1" value
 * @method string              getInternalName()        Returns the current record's "internal_name" value
 * @method string              getDocName()             Returns the current record's "doc_name" value
 * @method string              getSlug()                Returns the current record's "slug" value
 * @method integer             getOwnerId()             Returns the current record's "owner_id" value
 * @method integer             getUnitTypeId()          Returns the current record's "unit_type_id" value
 * @method double              getPriceUah()            Returns the current record's "price_uah" value
 * @method double              getPriceDiscountUah()    Returns the current record's "price_discount_uah" value
 * @method double              getCommissionPercent()   Returns the current record's "commission_percent" value
 * @method string              getShortDescription()    Returns the current record's "short_description" value
 * @method string              getDescription()         Returns the current record's "description" value
 * @method string              getTargetUse()           Returns the current record's "target_use" value
 * @method string              getPassengerCapacity()   Returns the current record's "passenger_capacity" value
 * @method string              getBasicInfo()           Returns the current record's "basic_info" value
 * @method string              getEquipment()           Returns the current record's "equipment" value
 * @method string              getCrew()                Returns the current record's "crew" value
 * @method string              getPassengerInsurance()  Returns the current record's "passenger_insurance" value
 * @method string              getPrice()               Returns the current record's "price" value
 * @method string              getAdditionalInfo()      Returns the current record's "additional_info" value
 * @method string              getInSight()             Returns the current record's "in_sight" value
 * @method string              getCatering()            Returns the current record's "catering" value
 * @method string              getInfoValue1()          Returns the current record's "info_value1" value
 * @method string              getInfoText1()           Returns the current record's "info_text1" value
 * @method string              getInfoValue2()          Returns the current record's "info_value2" value
 * @method string              getInfoText2()           Returns the current record's "info_text2" value
 * @method string              getInfoValue3()          Returns the current record's "info_value3" value
 * @method string              getInfoText3()           Returns the current record's "info_text3" value
 * @method string              getPriceValue1()         Returns the current record's "price_value1" value
 * @method string              getPriceText1()          Returns the current record's "price_text1" value
 * @method string              getPriceValue2()         Returns the current record's "price_value2" value
 * @method string              getPriceText2()          Returns the current record's "price_text2" value
 * @method string              getPriceValue3()         Returns the current record's "price_value3" value
 * @method string              getPriceText3()          Returns the current record's "price_text3" value
 * @method integer             getMainImageId()         Returns the current record's "main_image_id" value
 * @method integer             getOrder()               Returns the current record's "order" value
 * @method Owner               getOwner()               Returns the current record's "Owner" value
 * @method ItemUnitType        getUnitType()            Returns the current record's "UnitType" value
 * @method ItemImage           getMainImage()           Returns the current record's "MainImage" value
 * @method Doctrine_Collection getImages()              Returns the current record's "Images" collection
 * @method Doctrine_Collection getCategories()          Returns the current record's "Categories" collection
 * @method Doctrine_Collection getItemCategories()      Returns the current record's "ItemCategories" collection
 * @method Doctrine_Collection getOrders()              Returns the current record's "Orders" collection
 * @method Doctrine_Collection getItemOrders()          Returns the current record's "ItemOrders" collection
 * @method Item                setIsActive()            Sets the current record's "is_active" value
 * @method Item                setIsOwn()               Sets the current record's "is_own" value
 * @method Item                setHideAttractions()     Sets the current record's "hide_attractions" value
 * @method Item                setName()                Sets the current record's "name" value
 * @method Item                setTitle()               Sets the current record's "title" value
 * @method Item                setHtmlDescription()     Sets the current record's "html_description" value
 * @method Item                setHtmlKeywords()        Sets the current record's "html_keywords" value
 * @method Item                setMainImageTitle()      Sets the current record's "main_image_title" value
 * @method Item                setMainImageAlt()        Sets the current record's "main_image_alt" value
 * @method Item                setListingText()         Sets the current record's "listing_text" value
 * @method Item                setH1()                  Sets the current record's "h1" value
 * @method Item                setInternalName()        Sets the current record's "internal_name" value
 * @method Item                setDocName()             Sets the current record's "doc_name" value
 * @method Item                setSlug()                Sets the current record's "slug" value
 * @method Item                setOwnerId()             Sets the current record's "owner_id" value
 * @method Item                setUnitTypeId()          Sets the current record's "unit_type_id" value
 * @method Item                setPriceUah()            Sets the current record's "price_uah" value
 * @method Item                setPriceDiscountUah()    Sets the current record's "price_discount_uah" value
 * @method Item                setCommissionPercent()   Sets the current record's "commission_percent" value
 * @method Item                setShortDescription()    Sets the current record's "short_description" value
 * @method Item                setDescription()         Sets the current record's "description" value
 * @method Item                setTargetUse()           Sets the current record's "target_use" value
 * @method Item                setPassengerCapacity()   Sets the current record's "passenger_capacity" value
 * @method Item                setBasicInfo()           Sets the current record's "basic_info" value
 * @method Item                setEquipment()           Sets the current record's "equipment" value
 * @method Item                setCrew()                Sets the current record's "crew" value
 * @method Item                setPassengerInsurance()  Sets the current record's "passenger_insurance" value
 * @method Item                setPrice()               Sets the current record's "price" value
 * @method Item                setAdditionalInfo()      Sets the current record's "additional_info" value
 * @method Item                setInSight()             Sets the current record's "in_sight" value
 * @method Item                setCatering()            Sets the current record's "catering" value
 * @method Item                setInfoValue1()          Sets the current record's "info_value1" value
 * @method Item                setInfoText1()           Sets the current record's "info_text1" value
 * @method Item                setInfoValue2()          Sets the current record's "info_value2" value
 * @method Item                setInfoText2()           Sets the current record's "info_text2" value
 * @method Item                setInfoValue3()          Sets the current record's "info_value3" value
 * @method Item                setInfoText3()           Sets the current record's "info_text3" value
 * @method Item                setPriceValue1()         Sets the current record's "price_value1" value
 * @method Item                setPriceText1()          Sets the current record's "price_text1" value
 * @method Item                setPriceValue2()         Sets the current record's "price_value2" value
 * @method Item                setPriceText2()          Sets the current record's "price_text2" value
 * @method Item                setPriceValue3()         Sets the current record's "price_value3" value
 * @method Item                setPriceText3()          Sets the current record's "price_text3" value
 * @method Item                setMainImageId()         Sets the current record's "main_image_id" value
 * @method Item                setOrder()               Sets the current record's "order" value
 * @method Item                setOwner()               Sets the current record's "Owner" value
 * @method Item                setUnitType()            Sets the current record's "UnitType" value
 * @method Item                setMainImage()           Sets the current record's "MainImage" value
 * @method Item                setImages()              Sets the current record's "Images" collection
 * @method Item                setCategories()          Sets the current record's "Categories" collection
 * @method Item                setItemCategories()      Sets the current record's "ItemCategories" collection
 * @method Item                setOrders()              Sets the current record's "Orders" collection
 * @method Item                setItemOrders()          Sets the current record's "ItemOrders" collection
 * 
 * @package    Rentflot
 * @subpackage model
 * @author     Infosoft
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseItem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('item');
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('is_own', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('hide_attractions', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('html_description', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('html_keywords', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('main_image_title', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('main_image_alt', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('listing_text', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('h1', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('internal_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('doc_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('owner_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('unit_type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('price_uah', 'double', null, array(
             'type' => 'double',
             'notnull' => true,
             ));
        $this->hasColumn('price_discount_uah', 'double', null, array(
             'type' => 'double',
             'notnull' => true,
             ));
        $this->hasColumn('commission_percent', 'double', null, array(
             'type' => 'double',
             ));
        $this->hasColumn('short_description', 'string', 10000, array(
             'type' => 'string',
             'length' => 10000,
             ));
        $this->hasColumn('description', 'string', 10000, array(
             'type' => 'string',
             'length' => 10000,
             ));
        $this->hasColumn('target_use', 'string', 10000, array(
             'type' => 'string',
             'length' => 10000,
             ));
        $this->hasColumn('passenger_capacity', 'string', 10000, array(
             'type' => 'string',
             'length' => 10000,
             ));
        $this->hasColumn('basic_info', 'string', 10000, array(
             'type' => 'string',
             'length' => 10000,
             ));
        $this->hasColumn('equipment', 'string', 10000, array(
             'type' => 'string',
             'length' => 10000,
             ));
        $this->hasColumn('crew', 'string', 10000, array(
             'type' => 'string',
             'length' => 10000,
             ));
        $this->hasColumn('passenger_insurance', 'string', 10000, array(
             'type' => 'string',
             'length' => 10000,
             ));
        $this->hasColumn('price', 'string', 10000, array(
             'type' => 'string',
             'length' => 10000,
             ));
        $this->hasColumn('additional_info', 'string', 10000, array(
             'type' => 'string',
             'length' => 10000,
             ));
        $this->hasColumn('in_sight', 'string', 10000, array(
             'type' => 'string',
             'length' => 10000,
             ));
        $this->hasColumn('catering', 'string', 10000, array(
             'type' => 'string',
             'length' => 10000,
             ));
        $this->hasColumn('info_value1', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('info_text1', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('info_value2', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('info_text2', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('info_value3', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('info_text3', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('price_value1', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('price_text1', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('price_value2', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('price_text2', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('price_value3', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('price_text3', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('main_image_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('order', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Owner', array(
             'local' => 'owner_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('ItemUnitType as UnitType', array(
             'local' => 'unit_type_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('ItemImage as MainImage', array(
             'local' => 'main_image_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('ItemImage as Images', array(
             'local' => 'id',
             'foreign' => 'object_id',
             'orderBy' => 'order'));

        $this->hasMany('Category as Categories', array(
             'refClass' => 'CategoryItem',
             'local' => 'item_id',
             'foreign' => 'category_id'));

        $this->hasMany('CategoryItem as ItemCategories', array(
             'local' => 'id',
             'foreign' => 'item_id'));

        $this->hasMany('Order as Orders', array(
             'refClass' => 'OrderItem',
             'local' => 'item_id',
             'foreign' => 'order_id'));

        $this->hasMany('OrderItem as ItemOrders', array(
             'local' => 'id',
             'foreign' => 'item_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'title',
              2 => 'html_description',
              3 => 'main_image_title',
              4 => 'main_image_alt',
              5 => 'html_keywords',
              6 => 'listing_text',
              7 => 'h1',
              8 => 'short_description',
              9 => 'description',
              10 => 'target_use',
              11 => 'passenger_capacity',
              12 => 'basic_info',
              13 => 'equipment',
              14 => 'crew',
              15 => 'passenger_insurance',
              16 => 'price',
              17 => 'additional_info',
              18 => 'in_sight',
              19 => 'catering',
              20 => 'info_value1',
              21 => 'info_text1',
              22 => 'info_value2',
              23 => 'info_text2',
              24 => 'info_value3',
              25 => 'info_text3',
              26 => 'price_value1',
              27 => 'price_text1',
              28 => 'price_value2',
              29 => 'price_text2',
              30 => 'price_value3',
              31 => 'price_text3',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}