<?php

/**
 * BaseOrderItemStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $order
 * @property Doctrine_Collection $OrderItems
 * 
 * @method string              getName()       Returns the current record's "name" value
 * @method integer             getOrder()      Returns the current record's "order" value
 * @method Doctrine_Collection getOrderItems() Returns the current record's "OrderItems" collection
 * @method OrderItemStatus     setName()       Sets the current record's "name" value
 * @method OrderItemStatus     setOrder()      Sets the current record's "order" value
 * @method OrderItemStatus     setOrderItems() Sets the current record's "OrderItems" collection
 * 
 * @package    Rentflot
 * @subpackage model
 * @author     Infosoft
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrderItemStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('order_item_status');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('order', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1000,
             ));

        $this->option('orderBy', 'order');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('OrderItem as OrderItems', array(
             'local' => 'id',
             'foreign' => 'status_id'));
    }
}