<?php

/**
 * BaseItemImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $object_id
 * @property string $filename
 * @property integer $order
 * @property string $alt
 * @property string $title
 * @property string $alt_en
 * @property string $title_en
 * @property integer $width
 * @property integer $height
 * @property Doctrine_Collection $Itemes
 * @property Item $Item
 * 
 * @method integer             getObjectId()  Returns the current record's "object_id" value
 * @method string              getFilename()  Returns the current record's "filename" value
 * @method integer             getOrder()     Returns the current record's "order" value
 * @method string              getAlt()       Returns the current record's "alt" value
 * @method string              getTitle()     Returns the current record's "title" value
 * @method string              getAltEn()     Returns the current record's "alt_en" value
 * @method string              getTitleEn()   Returns the current record's "title_en" value
 * @method integer             getWidth()     Returns the current record's "width" value
 * @method integer             getHeight()    Returns the current record's "height" value
 * @method Doctrine_Collection getItemes()    Returns the current record's "Itemes" collection
 * @method Item                getItem()      Returns the current record's "Item" value
 * @method ItemImage           setObjectId()  Sets the current record's "object_id" value
 * @method ItemImage           setFilename()  Sets the current record's "filename" value
 * @method ItemImage           setOrder()     Sets the current record's "order" value
 * @method ItemImage           setAlt()       Sets the current record's "alt" value
 * @method ItemImage           setTitle()     Sets the current record's "title" value
 * @method ItemImage           setAltEn()     Sets the current record's "alt_en" value
 * @method ItemImage           setTitleEn()   Sets the current record's "title_en" value
 * @method ItemImage           setWidth()     Sets the current record's "width" value
 * @method ItemImage           setHeight()    Sets the current record's "height" value
 * @method ItemImage           setItemes()    Sets the current record's "Itemes" collection
 * @method ItemImage           setItem()      Sets the current record's "Item" value
 * 
 * @package    Rentflot
 * @subpackage model
 * @author     Infosoft
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseItemImage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('item_image');
        $this->hasColumn('object_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('filename', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('order', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('alt', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('alt_en', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('title_en', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('width', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('height', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Item as Itemes', array(
             'local' => 'id',
             'foreign' => 'main_image_id'));

        $this->hasOne('Item', array(
             'local' => 'object_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}