<?php

/**
 * BaseClientContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property timestamp $contact_date
 * @property time $contact_time
 * @property string $comment
 * @property integer $order_id
 * @property integer $contact_status_id
 * @property ContactStatus $ContactStatus
 * @property Order $Order
 * @property sfGuardUser $User
 * 
 * @method timestamp     getContactDate()       Returns the current record's "contact_date" value
 * @method time          getContactTime()       Returns the current record's "contact_time" value
 * @method string        getComment()           Returns the current record's "comment" value
 * @method integer       getOrderId()           Returns the current record's "order_id" value
 * @method integer       getContactStatusId()   Returns the current record's "contact_status_id" value
 * @method ContactStatus getContactStatus()     Returns the current record's "ContactStatus" value
 * @method Order         getOrder()             Returns the current record's "Order" value
 * @method sfGuardUser   getUser()              Returns the current record's "User" value
 * @method ClientContact setContactDate()       Sets the current record's "contact_date" value
 * @method ClientContact setContactTime()       Sets the current record's "contact_time" value
 * @method ClientContact setComment()           Sets the current record's "comment" value
 * @method ClientContact setOrderId()           Sets the current record's "order_id" value
 * @method ClientContact setContactStatusId()   Sets the current record's "contact_status_id" value
 * @method ClientContact setContactStatus()     Sets the current record's "ContactStatus" value
 * @method ClientContact setOrder()             Sets the current record's "Order" value
 * @method ClientContact setUser()              Sets the current record's "User" value
 * 
 * @package    Rentflot
 * @subpackage model
 * @author     Infosoft
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClientContact extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('client_contact');
        $this->hasColumn('contact_date', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('contact_time', 'time', null, array(
             'type' => 'time',
             'notnull' => true,
             ));
        $this->hasColumn('comment', 'string', 5000, array(
             'type' => 'string',
             'length' => 5000,
             ));
        $this->hasColumn('order_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('contact_status_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ContactStatus', array(
             'local' => 'contact_status_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Order', array(
             'local' => 'order_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'created_by',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}