<?php

/**
 * BaseAdvertisement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $slug
 * @property string $title
 * @property string $description
 * @property string $keywords
 * @property string $text
 * @property Doctrine_Collection $Categories
 * @property Doctrine_Collection $AdvertisementCategories
 * 
 * @method string              getName()                    Returns the current record's "name" value
 * @method string              getSlug()                    Returns the current record's "slug" value
 * @method string              getTitle()                   Returns the current record's "title" value
 * @method string              getDescription()             Returns the current record's "description" value
 * @method string              getKeywords()                Returns the current record's "keywords" value
 * @method string              getText()                    Returns the current record's "text" value
 * @method Doctrine_Collection getCategories()              Returns the current record's "Categories" collection
 * @method Doctrine_Collection getAdvertisementCategories() Returns the current record's "AdvertisementCategories" collection
 * @method Advertisement       setName()                    Sets the current record's "name" value
 * @method Advertisement       setSlug()                    Sets the current record's "slug" value
 * @method Advertisement       setTitle()                   Sets the current record's "title" value
 * @method Advertisement       setDescription()             Sets the current record's "description" value
 * @method Advertisement       setKeywords()                Sets the current record's "keywords" value
 * @method Advertisement       setText()                    Sets the current record's "text" value
 * @method Advertisement       setCategories()              Sets the current record's "Categories" collection
 * @method Advertisement       setAdvertisementCategories() Sets the current record's "AdvertisementCategories" collection
 * 
 * @package    Rentflot
 * @subpackage model
 * @author     Infosoft
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdvertisement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('advertisement');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 2000, array(
             'type' => 'string',
             'length' => 2000,
             ));
        $this->hasColumn('keywords', 'string', 2000, array(
             'type' => 'string',
             'length' => 2000,
             ));
        $this->hasColumn('text', 'string', 10000, array(
             'type' => 'string',
             'length' => 10000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Category as Categories', array(
             'refClass' => 'CategoryAdvertisement',
             'local' => 'advertisement_id',
             'foreign' => 'category_id'));

        $this->hasMany('CategoryAdvertisement as AdvertisementCategories', array(
             'local' => 'id',
             'foreign' => 'advertisement_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'title',
              2 => 'description',
              3 => 'keywords',
              4 => 'text',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}