<?php

/**
 * BaseCategoryItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property integer $item_id
 * @property Category $Category
 * @property Item $Item
 * 
 * @method integer      getCategoryId()  Returns the current record's "category_id" value
 * @method integer      getItemId()      Returns the current record's "item_id" value
 * @method Category     getCategory()    Returns the current record's "Category" value
 * @method Item         getItem()        Returns the current record's "Item" value
 * @method CategoryItem setCategoryId()  Sets the current record's "category_id" value
 * @method CategoryItem setItemId()      Sets the current record's "item_id" value
 * @method CategoryItem setCategory()    Sets the current record's "Category" value
 * @method CategoryItem setItem()        Sets the current record's "Item" value
 * 
 * @package    Rentflot
 * @subpackage model
 * @author     Infosoft
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoryItem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category_item');
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('item_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Item', array(
             'local' => 'item_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}