<?php

/**
 * BaseArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $slug
 * @property string $content
 * @property string $title
 * @property string $description
 * @property string $keywords
 * @property string $h1
 * 
 * @method string  getName()        Returns the current record's "name" value
 * @method string  getSlug()        Returns the current record's "slug" value
 * @method string  getContent()     Returns the current record's "content" value
 * @method string  getTitle()       Returns the current record's "title" value
 * @method string  getDescription() Returns the current record's "description" value
 * @method string  getKeywords()    Returns the current record's "keywords" value
 * @method string  getH1()          Returns the current record's "h1" value
 * @method Article setName()        Sets the current record's "name" value
 * @method Article setSlug()        Sets the current record's "slug" value
 * @method Article setContent()     Sets the current record's "content" value
 * @method Article setTitle()       Sets the current record's "title" value
 * @method Article setDescription() Sets the current record's "description" value
 * @method Article setKeywords()    Sets the current record's "keywords" value
 * @method Article setH1()          Sets the current record's "h1" value
 * 
 * @package    Rentflot
 * @subpackage model
 * @author     Infosoft
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArticle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('article');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('content', 'string', 10000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10000,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 2000, array(
             'type' => 'string',
             'length' => 2000,
             ));
        $this->hasColumn('keywords', 'string', 2000, array(
             'type' => 'string',
             'length' => 2000,
             ));
        $this->hasColumn('h1', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'content',
              2 => 'title',
              3 => 'description',
              4 => 'keywords',
              5 => 'h1',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}