<?php

/**
 * BasePierf
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $link
 * @property string $name_english
 * @property string $link_english
 * 
 * @method string getName()         Returns the current record's "name" value
 * @method string getLink()         Returns the current record's "link" value
 * @method string getNameEnglish()  Returns the current record's "name_english" value
 * @method string getLinkEnglish()  Returns the current record's "link_english" value
 * @method Pierf  setName()         Sets the current record's "name" value
 * @method Pierf  setLink()         Sets the current record's "link" value
 * @method Pierf  setNameEnglish()  Sets the current record's "name_english" value
 * @method Pierf  setLinkEnglish()  Sets the current record's "link_english" value
 * 
 * @package    Rentflot
 * @subpackage model
 * @author     Infosoft
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePierf extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pierf');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('link', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('name_english', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('link_english', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}