<?php

/**
 * BasePierFrontend
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $link
 * 
 * @method string       getName() Returns the current record's "name" value
 * @method string       getLink() Returns the current record's "link" value
 * @method PierFrontend setName() Sets the current record's "name" value
 * @method PierFrontend setLink() Sets the current record's "link" value
 * 
 * @package    Rentflot
 * @subpackage model
 * @author     Infosoft
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePierFrontend extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pier_frontend');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('link', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}