<?php

/**
 * BaseSpd
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $spd_name
 * @property string $spd_name_genitive
 * @property string $details
 * @property Doctrine_Collection $Orders
 * 
 * @method string              getName()              Returns the current record's "name" value
 * @method string              getSpdName()           Returns the current record's "spd_name" value
 * @method string              getSpdNameGenitive()   Returns the current record's "spd_name_genitive" value
 * @method string              getDetails()           Returns the current record's "details" value
 * @method Doctrine_Collection getOrders()            Returns the current record's "Orders" collection
 * @method Spd                 setName()              Sets the current record's "name" value
 * @method Spd                 setSpdName()           Sets the current record's "spd_name" value
 * @method Spd                 setSpdNameGenitive()   Sets the current record's "spd_name_genitive" value
 * @method Spd                 setDetails()           Sets the current record's "details" value
 * @method Spd                 setOrders()            Sets the current record's "Orders" collection
 * 
 * @package    Rentflot
 * @subpackage model
 * @author     Infosoft
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSpd extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('spd');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('spd_name', 'string', 500, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 500,
             ));
        $this->hasColumn('spd_name_genitive', 'string', 500, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 500,
             ));
        $this->hasColumn('details', 'string', 5000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 5000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Order as Orders', array(
             'local' => 'id',
             'foreign' => 'spd_id'));
    }
}