<?php

/**
 * BaseActionLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $username
 * @property string $module
 * @property string $action
 * @property string $ip
 * @property string $ids
 * @property string $description
 * 
 * @method string    getUsername()    Returns the current record's "username" value
 * @method string    getModule()      Returns the current record's "module" value
 * @method string    getAction()      Returns the current record's "action" value
 * @method string    getIp()          Returns the current record's "ip" value
 * @method string    getIds()         Returns the current record's "ids" value
 * @method string    getDescription() Returns the current record's "description" value
 * @method ActionLog setUsername()    Sets the current record's "username" value
 * @method ActionLog setModule()      Sets the current record's "module" value
 * @method ActionLog setAction()      Sets the current record's "action" value
 * @method ActionLog setIp()          Sets the current record's "ip" value
 * @method ActionLog setIds()         Sets the current record's "ids" value
 * @method ActionLog setDescription() Sets the current record's "description" value
 * 
 * @package    Rentflot
 * @subpackage model
 * @author     Infosoft
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseActionLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('action_log');
        $this->hasColumn('username', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('module', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('action', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('ip', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('ids', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}