<?php

/**
 * BaseOrderType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $order
 * @property Doctrine_Collection $Orders
 * 
 * @method string              getName()   Returns the current record's "name" value
 * @method integer             getOrder()  Returns the current record's "order" value
 * @method Doctrine_Collection getOrders() Returns the current record's "Orders" collection
 * @method OrderType           setName()   Sets the current record's "name" value
 * @method OrderType           setOrder()  Sets the current record's "order" value
 * @method OrderType           setOrders() Sets the current record's "Orders" collection
 * 
 * @package    Rentflot
 * @subpackage model
 * @author     Infosoft
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrderType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('order_type');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('order', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1000,
             ));

        $this->option('orderBy', 'order');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Order as Orders', array(
             'local' => 'id',
             'foreign' => 'order_type_id'));
    }
}