<?php

/**
 * BaseOwner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $org_name
 * @property string $name
 * @property string $address
 * @property string $phones
 * @property string $email
 * @property string $additional_information
 * @property sfGuardUser $User
 * @property Doctrine_Collection $Items
 * 
 * @method integer             getUserId()                 Returns the current record's "user_id" value
 * @method string              getOrgName()                Returns the current record's "org_name" value
 * @method string              getName()                   Returns the current record's "name" value
 * @method string              getAddress()                Returns the current record's "address" value
 * @method string              getPhones()                 Returns the current record's "phones" value
 * @method string              getEmail()                  Returns the current record's "email" value
 * @method string              getAdditionalInformation()  Returns the current record's "additional_information" value
 * @method sfGuardUser         getUser()                   Returns the current record's "User" value
 * @method Doctrine_Collection getItems()                  Returns the current record's "Items" collection
 * @method Owner               setUserId()                 Sets the current record's "user_id" value
 * @method Owner               setOrgName()                Sets the current record's "org_name" value
 * @method Owner               setName()                   Sets the current record's "name" value
 * @method Owner               setAddress()                Sets the current record's "address" value
 * @method Owner               setPhones()                 Sets the current record's "phones" value
 * @method Owner               setEmail()                  Sets the current record's "email" value
 * @method Owner               setAdditionalInformation()  Sets the current record's "additional_information" value
 * @method Owner               setUser()                   Sets the current record's "User" value
 * @method Owner               setItems()                  Sets the current record's "Items" collection
 * 
 * @package    Rentflot
 * @subpackage model
 * @author     Infosoft
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOwner extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('owner');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('org_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('address', 'string', 5000, array(
             'type' => 'string',
             'length' => 5000,
             ));
        $this->hasColumn('phones', 'string', 5000, array(
             'type' => 'string',
             'length' => 5000,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('additional_information', 'string', 5000, array(
             'type' => 'string',
             'length' => 5000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('Item as Items', array(
             'local' => 'id',
             'foreign' => 'owner_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}