<?php

/**
 * BaseContactStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $ClientContact
 * 
 * @method string              getName()          Returns the current record's "name" value
 * @method Doctrine_Collection getClientContact() Returns the current record's "ClientContact" collection
 * @method ContactStatus       setName()          Sets the current record's "name" value
 * @method ContactStatus       setClientContact() Sets the current record's "ClientContact" collection
 * 
 * @package    Rentflot
 * @subpackage model
 * @author     Infosoft
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContactStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contact_status');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ClientContact', array(
             'local' => 'id',
             'foreign' => 'contact_status_id'));
    }
}