<?php

/**
 * BaseCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property boolean $is_hidden
 * @property integer $parent_id
 * @property string $name
 * @property string $slug
 * @property string $category_template
 * @property string $product_template
 * @property string $title
 * @property string $description
 * @property string $keywords
 * @property string $seo_short_text
 * @property string $seo_full_text
 * @property string $h1
 * @property string $item_title
 * @property string $item_description
 * @property string $item_keywords
 * @property string $item_h1
 * @property string $item_contacts
 * @property integer $order
 * @property Category $ParentCategory
 * @property Doctrine_Collection $Items
 * @property Doctrine_Collection $Advertisements
 * @property Doctrine_Collection $ChildCategories
 * @property Doctrine_Collection $CategoryAdvertisements
 * @property Doctrine_Collection $CategoryItems
 * 
 * @method boolean             getIsHidden()               Returns the current record's "is_hidden" value
 * @method integer             getParentId()               Returns the current record's "parent_id" value
 * @method string              getName()                   Returns the current record's "name" value
 * @method string              getSlug()                   Returns the current record's "slug" value
 * @method string              getCategoryTemplate()       Returns the current record's "category_template" value
 * @method string              getProductTemplate()        Returns the current record's "product_template" value
 * @method string              getTitle()                  Returns the current record's "title" value
 * @method string              getDescription()            Returns the current record's "description" value
 * @method string              getKeywords()               Returns the current record's "keywords" value
 * @method string              getSeoShortText()           Returns the current record's "seo_short_text" value
 * @method string              getSeoFullText()            Returns the current record's "seo_full_text" value
 * @method string              getH1()                     Returns the current record's "h1" value
 * @method string              getItemTitle()              Returns the current record's "item_title" value
 * @method string              getItemDescription()        Returns the current record's "item_description" value
 * @method string              getItemKeywords()           Returns the current record's "item_keywords" value
 * @method string              getItemH1()                 Returns the current record's "item_h1" value
 * @method string              getItemContacts()           Returns the current record's "item_contacts" value
 * @method integer             getOrder()                  Returns the current record's "order" value
 * @method Category            getParentCategory()         Returns the current record's "ParentCategory" value
 * @method Doctrine_Collection getItems()                  Returns the current record's "Items" collection
 * @method Doctrine_Collection getAdvertisements()         Returns the current record's "Advertisements" collection
 * @method Doctrine_Collection getChildCategories()        Returns the current record's "ChildCategories" collection
 * @method Doctrine_Collection getCategoryAdvertisements() Returns the current record's "CategoryAdvertisements" collection
 * @method Doctrine_Collection getCategoryItems()          Returns the current record's "CategoryItems" collection
 * @method Category            setIsHidden()               Sets the current record's "is_hidden" value
 * @method Category            setParentId()               Sets the current record's "parent_id" value
 * @method Category            setName()                   Sets the current record's "name" value
 * @method Category            setSlug()                   Sets the current record's "slug" value
 * @method Category            setCategoryTemplate()       Sets the current record's "category_template" value
 * @method Category            setProductTemplate()        Sets the current record's "product_template" value
 * @method Category            setTitle()                  Sets the current record's "title" value
 * @method Category            setDescription()            Sets the current record's "description" value
 * @method Category            setKeywords()               Sets the current record's "keywords" value
 * @method Category            setSeoShortText()           Sets the current record's "seo_short_text" value
 * @method Category            setSeoFullText()            Sets the current record's "seo_full_text" value
 * @method Category            setH1()                     Sets the current record's "h1" value
 * @method Category            setItemTitle()              Sets the current record's "item_title" value
 * @method Category            setItemDescription()        Sets the current record's "item_description" value
 * @method Category            setItemKeywords()           Sets the current record's "item_keywords" value
 * @method Category            setItemH1()                 Sets the current record's "item_h1" value
 * @method Category            setItemContacts()           Sets the current record's "item_contacts" value
 * @method Category            setOrder()                  Sets the current record's "order" value
 * @method Category            setParentCategory()         Sets the current record's "ParentCategory" value
 * @method Category            setItems()                  Sets the current record's "Items" collection
 * @method Category            setAdvertisements()         Sets the current record's "Advertisements" collection
 * @method Category            setChildCategories()        Sets the current record's "ChildCategories" collection
 * @method Category            setCategoryAdvertisements() Sets the current record's "CategoryAdvertisements" collection
 * @method Category            setCategoryItems()          Sets the current record's "CategoryItems" collection
 * 
 * @package    Rentflot
 * @subpackage model
 * @author     Infosoft
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category');
        $this->hasColumn('is_hidden', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('parent_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('category_template', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('product_template', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 2000, array(
             'type' => 'string',
             'length' => 2000,
             ));
        $this->hasColumn('keywords', 'string', 2000, array(
             'type' => 'string',
             'length' => 2000,
             ));
        $this->hasColumn('seo_short_text', 'string', 2000, array(
             'type' => 'string',
             'length' => 2000,
             ));
        $this->hasColumn('seo_full_text', 'string', 2000, array(
             'type' => 'string',
             'length' => 2000,
             ));
        $this->hasColumn('h1', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('item_title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('item_description', 'string', 2000, array(
             'type' => 'string',
             'length' => 2000,
             ));
        $this->hasColumn('item_keywords', 'string', 2000, array(
             'type' => 'string',
             'length' => 2000,
             ));
        $this->hasColumn('item_h1', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('item_contacts', 'string', 2000, array(
             'type' => 'string',
             'length' => 2000,
             ));
        $this->hasColumn('order', 'integer', null, array(
             'type' => 'integer',
             'default' => 1000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Category as ParentCategory', array(
             'local' => 'parent_id',
             'foreign' => 'id'));

        $this->hasMany('Item as Items', array(
             'refClass' => 'CategoryItem',
             'local' => 'category_id',
             'foreign' => 'item_id',
             'orderBy' => 'order'));

        $this->hasMany('Advertisement as Advertisements', array(
             'refClass' => 'CategoryAdvertisement',
             'local' => 'category_id',
             'foreign' => 'advertisement_id'));

        $this->hasMany('Category as ChildCategories', array(
             'local' => 'id',
             'foreign' => 'parent_id'));

        $this->hasMany('CategoryAdvertisement as CategoryAdvertisements', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $this->hasMany('CategoryItem as CategoryItems', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'title',
              2 => 'description',
              3 => 'seo_short_text',
              4 => 'seo_full_text',
              5 => 'keywords',
              6 => 'h1',
              7 => 'item_title',
              8 => 'item_description',
              9 => 'item_keywords',
              10 => 'item_h1',
              11 => 'item_contacts',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}