<?php

/**
 * BaseItemTempImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $object_id
 * @property string $filename
 * @property integer $order
 * @property string $alt
 * @property string $title
 * @property string $alt_en
 * @property string $title_en
 * @property integer $width
 * @property integer $height
 * 
 * @method string        getObjectId()  Returns the current record's "object_id" value
 * @method string        getFilename()  Returns the current record's "filename" value
 * @method integer       getOrder()     Returns the current record's "order" value
 * @method string        getAlt()       Returns the current record's "alt" value
 * @method string        getTitle()     Returns the current record's "title" value
 * @method string        getAltEn()     Returns the current record's "alt_en" value
 * @method string        getTitleEn()   Returns the current record's "title_en" value
 * @method integer       getWidth()     Returns the current record's "width" value
 * @method integer       getHeight()    Returns the current record's "height" value
 * @method ItemTempImage setObjectId()  Sets the current record's "object_id" value
 * @method ItemTempImage setFilename()  Sets the current record's "filename" value
 * @method ItemTempImage setOrder()     Sets the current record's "order" value
 * @method ItemTempImage setAlt()       Sets the current record's "alt" value
 * @method ItemTempImage setTitle()     Sets the current record's "title" value
 * @method ItemTempImage setAltEn()     Sets the current record's "alt_en" value
 * @method ItemTempImage setTitleEn()   Sets the current record's "title_en" value
 * @method ItemTempImage setWidth()     Sets the current record's "width" value
 * @method ItemTempImage setHeight()    Sets the current record's "height" value
 * 
 * @package    Rentflot
 * @subpackage model
 * @author     Infosoft
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseItemTempImage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('item_temp_image');
        $this->hasColumn('object_id', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 32,
             ));
        $this->hasColumn('filename', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('order', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('alt', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('alt_en', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('title_en', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('width', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('height', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}