<?php

/**
 * BaseBill
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $type_id
 * @property integer $index_id
 * @property string $name
 * @property string $description
 * @property double $amount_uah
 * @property double $amount_payed_uah
 * @property BillType $Type
 * @property BillIndex $Index
 * 
 * @method integer   getTypeId()           Returns the current record's "type_id" value
 * @method integer   getIndexId()          Returns the current record's "index_id" value
 * @method string    getName()             Returns the current record's "name" value
 * @method string    getDescription()      Returns the current record's "description" value
 * @method double    getAmountUah()        Returns the current record's "amount_uah" value
 * @method double    getAmountPayedUah()   Returns the current record's "amount_payed_uah" value
 * @method BillType  getType()             Returns the current record's "Type" value
 * @method BillIndex getIndex()            Returns the current record's "Index" value
 * @method Bill      setTypeId()           Sets the current record's "type_id" value
 * @method Bill      setIndexId()          Sets the current record's "index_id" value
 * @method Bill      setName()             Sets the current record's "name" value
 * @method Bill      setDescription()      Sets the current record's "description" value
 * @method Bill      setAmountUah()        Sets the current record's "amount_uah" value
 * @method Bill      setAmountPayedUah()   Sets the current record's "amount_payed_uah" value
 * @method Bill      setType()             Sets the current record's "Type" value
 * @method Bill      setIndex()            Sets the current record's "Index" value
 * 
 * @package    Rentflot
 * @subpackage model
 * @author     Infosoft
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBill extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bill');
        $this->hasColumn('type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('index_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 2000, array(
             'type' => 'string',
             'length' => 2000,
             ));
        $this->hasColumn('amount_uah', 'double', null, array(
             'type' => 'double',
             'notnull' => true,
             ));
        $this->hasColumn('amount_payed_uah', 'double', null, array(
             'type' => 'double',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BillType as Type', array(
             'local' => 'type_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'orderBy' => 'order'));

        $this->hasOne('BillIndex as Index', array(
             'local' => 'index_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'orderBy' => 'order'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}