showItemSuccess:
  stylesheets:
    - /magicLibsPlugin/jquery/plugins/lightbox-0.5/css/jquery.lightbox-0.5.css
#    - /magicLibsPlugin/jquery/jquery-ui/infosoft3/jquery-ui-1.8.7.custom.css
    - jquery-ui/rf/jquery-ui-1.8.16.custom.css
  javascripts:
    - /magicLibsPlugin/jquery/plugins/lightbox-0.5/js/jquery.lightbox-0.5.js
    - /magicLibsPlugin/jquery/jquery-ui/jquery-ui-1.8.7.magic.js
    - /magicLibsPlugin/jquery/jquery-ui/jquery-ui-i18n.js
    - online_order.js
showCategorySuccess:
  stylesheets:
    - /magicLibsPlugin/jquery/plugins/lightbox-0.5/css/jquery.lightbox-0.5.css
#    - /magicLibsPlugin/jquery/jquery-ui/infosoft3/jquery-ui-1.8.7.custom.css
    - jquery-ui/rf/jquery-ui-1.8.16.custom.css
  javascripts:
    - /magicLibsPlugin/jquery/plugins/lightbox-0.5/js/jquery.lightbox-0.5.js
    - /magicLibsPlugin/jquery/jquery-ui/jquery-ui-1.8.7.magic.js
    - /magicLibsPlugin/jquery/jquery-ui/jquery-ui-i18n.js
    - online_order.js
