<?php

/**
 * ArticleTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticleTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object ArticleTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Article');
  }

  public function orderByName(Doctrine_Query $q, $direction = 'asc')
  {
    $q->leftJoin($q->getRootAlias() . '.Translation t WITH t.lang = \'' . sfContext::getInstance()->getUser()->getCulture() . '\' ');
    $q->orderBy('t.name ' . $direction);

    return $q;
  }

  public function retrieveArticleList(Doctrine_Query $q)
  {
    $rootAlias = $q->getRootAlias();

    $q->leftJoin($rootAlias . '.Translation t WITH t.lang = \'' . sfContext::getInstance()->getUser()->getCulture() . '\'');

    return $q;
  }
}