<?php

/**
 * BillTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BillTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object BillTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Bill');
  }

  public function orderByIndexName(Doctrine_Query $q, $direction = 'asc')
  {
    $q->leftJoin($q->getRootAlias() . '.Index i');
    $q->orderBy('i.name ' . $direction);
    return $q;
  }

  public function orderByTypeName(Doctrine_Query $q, $direction = 'asc')
  {
    $q->leftJoin($q->getRootAlias() . '.Type t');
    $q->orderBy('t.name ' . $direction);
    return $q;
  }

  public function retrieveBillList(Doctrine_Query $q)
  {
    $rootAlias = $q->getRootAlias();

    $q->innerJoin($rootAlias . '.Type t')
      ->leftJoin($rootAlias . '.Index i');

    return $q;
  }


}