<?php

/**
 * BillIndexTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BillIndexTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BillIndexTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BillIndex');
    }
}