<?php

/**
 * CategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object CategoryTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('Category');
  }

  /**
   * @param Doctrine_Query $q
   * @return Doctrine_Query
   */
  public function retrieveCategoryList(Doctrine_Query $q)
  {
    $root_alias = $q->getRootAlias();
    $culture = sfContext::getInstance()->getUser()->getCulture();

    $q->leftJoin($root_alias.'.Translation t WITH t.lang = \''.$culture.'\'')
      ->leftJoin($root_alias.'.ParentCategory p');

    return $q;
  }

  public function orderByName(Doctrine_Query $q, $direction = 'asc')
  {
    $q->orderBy('t.name '.$direction);
    return $q;
  }

  public function orderParentName(Doctrine_Query $q, $direction = 'asc')
  {
    $q->orderBy('t.name '.$direction);
    return $q;
  }

}