<?php

/**
 * CategoryItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategoryItem');
    }
}