<?php

/**
 * CategoryAdvertisementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryAdvertisementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryAdvertisementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategoryAdvertisement');
    }
}