<?php

/**
 * Client
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Rentflot
 * @subpackage model
 * @author     Infosoft
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Client extends BaseClient
{
  
  public function __toString()
  {
    $client_name = array();
    if ($this->getOrgName()) 
    {
      $client_name[] = $this->getOrgName();
    }
    
    $client_name[] = $this->getName();
    
    if ($this->getPhones())
    {
      $client_name[] = $this->getPhones();
    }
    
      
    return implode(', ', $client_name);
    //return $this->getFullName();
  }
  
  public function getSpecialName()
  {
	return $this->__toString();
  }
  
  public function getFullName()
  {
    if ($this->getOrgName()) 
    {
      return $this->getOrgName().' ('.$this->getName().')';
    }
    return $this->getName();
  }
  
  public function getFullName2()
  {
    if ($this->getOrgName()) 
    {
      return $this->getOrgName().'<br />'.$this->getName();
    }
    return $this->getName();
  }
    
  public function getContactInfo()
  {
    return ($this->getPhones() ?  $this->getPhones().'<br />' : '').$this->getEmail();
  }
  
}