<?php

/**
 * ClientContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClientContactTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClientContactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClientContact');
    }
	
	/*
	  public function orderByOrderId(Doctrine_Query $q, $direction = 'asc')
	  {
		$q->orderBy($q->getRootAlias() . '.Order.id ' . $direction);
		return $q;
	  }
	  
	  public function orderByClientName(Doctrine_Query $q, $direction = 'asc')
	  {
		$q->orderBy($q->getRootAlias() . '.Order.Client.Name ' . $direction);
		return $q;
	  }	  
	*/
	
	public function retrievContactsNoContract(Doctrine_Query $q)
	{
		/*
		
		//this function can be deleted
		$rootAlias=$q->getRootAlias();
		
		//выбираем контакты, по которым нет контрактов
		$q_to_show="SELECT id FROM(select co.id,co.contact_date
FROM client_contact co, Client cl
LEFT JOIN `Order` ord ON cl.id=ord.client_id
WHERE cl.id=co.client_id
GROUP BY co.id
HAVING MAX(IFNULL(ord.created_at,'2010-01-01 00:00:00'))<co.contact_date) sub";
		$contacts_ids = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($q_to_show);	
		$co_ids=array();
		$co_ids[]=-100;
		foreach($contacts_ids as $cur_id)
		{
			$co_ids[]=$cur_id["id"];
		}
		
		//print_r($co_ids);
		//die;
		
		$q
		->leftJoin($rootAlias.'.Client c')
		->leftJoin('c.Orders o')
		->whereIn($rootAlias.'.id',$co_ids)
		;
		//echo $q->getSqlQuery();
		//die;
		*/
		return $q;
	}
}