<?php

/**
 * ClientTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClientTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object ClientTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Client');
  }

  static public function getUnknownClient()
  {
    $client = Doctrine::getTable('Client')->findOneById(sfConfig::get('app_order_unknown_client_id'));

    if (!$client)
    {
      $client = new Client();
      $client->setId(sfConfig::get('app_order_unknown_client_id'));
    }

    return $client;
  }
}