<?php

/**
 * ClientContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Rentflot
 * @subpackage model
 * @author     Infosoft
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ClientContact extends BaseClientContact
{
	/*
	public function getContactDateFormatted()
	{
		return format_date($this->getContactDate(),"D");
	}
	public function getClientName()
	{
		return $this->getClient()->getSpecialName();
	}
	*/
}