<?php

/**
 * ContactStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContactStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContactStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContactStatus');
    }
}