<?php

/**
 * FeedbackSubjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FeedbackSubjectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FeedbackSubjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FeedbackSubject');
    }
}