<?php

/**
 * ItemTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ItemTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object ItemTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Item');
  }

  public function orderByName(Doctrine_Query $q, $direction = 'asc')
  {
    $q->orderBy('t.name ' . $direction);
    return $q;
  }

  public function retrieveItemList(Doctrine_Query $q)
  {
    $rootAlias = $q->getRootAlias();

    $q->leftJoin($rootAlias . '.Translation t WITH t.lang = \'' . sfContext::getInstance()->getUser()->getCulture() . '\'')
      ->leftJoin($rootAlias . '.Owner o')
      ->leftJoin($rootAlias . '.Categories c')
      ->leftJoin($rootAlias . '.MainImage mim');

    return $q;
  }

  public function orderByOwnerName(Doctrine_Query $q, $direction = 'asc')
  {
    $q->orderBy('o.name ' . $direction);
    return $q;
  }
}