<?php

/**
 * ItemImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ItemImageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ItemImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ItemImage');
    }
}