<?php

/**
 * Item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Rentflot
 * @subpackage model
 * @author     Infosoft
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Item extends BaseItem
{
  public function getFullName()
  {
    // + название первой категории
    return $this->getName();
  
  }
  
  public function getOwnerName()
  {
    return $this->getOwner() ? $this->getOwner()->getName() : '';
  }
  
  public function getItemWithCategory()
  {
    $name = $this->getCategories()->getFirst() ? $this->getCategories()->getFirst()->getName().' &mdash; '.$this : $this;
    return $name;
  }


  public function getOnlineOrderItemName()
  {
    return $this . ($this->getCategories()->getFirst() ? ' &mdash; '.$this->getCategories()->getFirst()->getName() : '');
  }

  public function isCurrentUserIsOwner()
  {
    $sfGuardUser = sfContext::getInstance()->getUser()->getGuardUser();
    if ($this->relatedExists('Owner') &&
        $this->getOwner()->relatedExists('User') &&
        $sfGuardUser &&
        $this->getOwner()->getUser()->getId() == $sfGuardUser->getId())
    {
      return true;
    }

    return false;
  }


  public function getImagesCount()
  {
    return Doctrine::getTable('ItemImage')->
      createQuery('im')->
      where('im.object_id = ?', $this->getId())->
      count();
  }

  public function getCleanedName()
  {
     return str_replace(array('"', "'"), '', $this->getName());
  }

}