<?php

/**
 * ItemImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Rentflot
 * @subpackage model
 * @author     Infosoft
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ItemImage extends BaseItemImage
{
  public function getAltByLang($lang, $i)
  {
    if($this->getAlt()!="")
    {
      echo $lang=="ru"?$this->getAlt():$this->getAltEn();
    }
    else
    {
      echo htmlspecialchars($this->getItem()->getCleanedName(ESC_RAW)).", ".__('photo', array(), 'catalog').($i+1);
    }
  }
  public  function  getTitleByLang($lang, $i)
  {
    if($this->getTitle()!="")
    {
      echo $lang=="ru"?$this->getTitle():$this->getTitleEn();
    }
    else
    {
      echo htmlspecialchars($this->getItem()->getCleanedName(ESC_RAW)).", ".__('photo', array(), 'catalog').($i+1);
    }
  }
  public  function  getDescriptionByLang($lang, $i)
  {
    $text="";
    if($this->getAlt()!="")
    {
      $text= $lang=="ru"?$this->getAlt():$this->getAltEn();
    }
    else
    {
      $text= htmlspecialchars($this->getItem()->getCleanedName(ESC_RAW)).", ".__('photo', array(), 'catalog').($i+1);
    }


    if(strpos($text,'- компания Рентфлот'))
    {
      $ind=strpos($text,'- компания Рентфлот');
      $text=substr($text,0,$ind);
    }
    if(strpos($text,'- Rentflot Company'))
    {
      $ind=strpos($text,'- Rentflot Company');
      $text=substr($text,0,$ind);
    }
    //echo "xxxxxxxx".$text;
    //echo "xxxxxxxx".$text;
    //die;
    echo $text;
  }
}