<?php

/**
 * ItemTempImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ItemTempImageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ItemTempImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ItemTempImage');
    }
}