<?php

/**
 * ItemUnitTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ItemUnitTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ItemUnitTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ItemUnitType');
    }
}