<?php

/**
 * KitchenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class KitchenTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object KitchenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Kitchen');
    }
}