<?php

/**
 * OrderTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrderTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object OrderTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Order');
  }

  public function orderByClientName(Doctrine_Query $q, $direction = 'asc')
  {
    $q->orderBy($q->getRootAlias() . '.Client.name ' . $direction);
    return $q;
  }

  public function orderByTime(Doctrine_Query $q, $direction = 'asc')
  {
    $q->orderBy($q->getRootAlias() . '.time_from ' . $direction);
    return $q;
  }

  public function orderByOrderTypeName(Doctrine_Query $q, $direction = 'asc')
  {
    $q->orderBy($q->getRootAlias() . '.OrderType.name ' . $direction);
    return $q;
  }

  public function retrieveOrderList(Doctrine_Query $q)
  {
    $root_alias = $q->getRootAlias();
    $q->leftJoin($root_alias . '.OrderItems oi')
      ->leftJoin('oi.Status ois')
      ->leftJoin('oi.Item i')
      ->leftJoin($root_alias . '.OrderType ot')
      ->leftJoin($root_alias . '.Client c')
      ->leftJoin($root_alias . '.Items is');
      //->orderBy($root_alias.'.created_at DESC');

    return $q;
  }
}