<?php

/**
 * OrderItemStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrderItemStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrderItemStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrderItemStatus');
    }
}