<?php

/**
 * OwnerTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OwnerTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object OwnerTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Owner');
  }

  public function retrieveOwnerList(Doctrine_Query $q)
  {
    $rootAlias = $q->getRootAlias();

    $q->leftJoin($rootAlias . '.User u')
      ->leftJoin($rootAlias . '.Items i')
      ->leftJoin('i.Translation it WITH it.lang = \'' . sfContext::getInstance()->getUser()->getCulture() . '\'');

    return $q;
  }

  public function orderByUsername(Doctrine_Query $q, $direction = 'asc')
  {
    $q->orderBy('u.username ' . $direction);

    return $q;
  }
}