<?php

/**
 * PierfTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PierfTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PierfTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pierf');
    }
}