<?php

/**
 * PierFrontendTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PierFrontendTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PierFrontendTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PierFrontend');
    }
}