<?php

/**
 * PierTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PierTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PierTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pier');
    }
}