<?php

/**
 * SpdTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SpdTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SpdTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Spd');
    }
}