<?php

/**
 * sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    CA Web
 * @subpackage model
 * @author     Infosoft
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{
		
  public function getShortName()
  {    
		$last_name = $this->getProfile()->getLastName();
    $first_name_initial = mb_convert_case(mb_substr($this->getProfile()->getFirstName(), 0, 1, 'UTF-8'), MB_CASE_UPPER, 'UTF-8');
    $patronymic_initial = mb_convert_case(mb_substr($this->getProfile()->getPatronymic(), 0, 1, 'UTF-8'), MB_CASE_UPPER, 'UTF-8');
    $short_name = trim(($last_name ? $last_name : '').' '.($first_name_initial ? $first_name_initial.'.' : '').' '.($patronymic_initial ? $patronymic_initial.'.' : ''));
    return $short_name ? $short_name : $this->getUserName();
  }
    
    
    public function getName()
		{
      return $this->getUserLastName().' '.$this->getUserFirstName();
    }
    
		public function getUserFirstName()
		{
			$user_profile = $this->getProfile();
			if (!empty($user_profile)) {
			  $first_name = $user_profile->getFirstName();
			} else $first_name = '';
			return $first_name;
		}

		
		public function getUserLastName()
		{
			$user_profile = $this->getProfile();
			if (!empty($user_profile)) {
			  $last_name = $user_profile->getLastName();
			} else $last_name = '';
			return $last_name;
		}
		

		public function getUserGroupName()
		{
			$groups = $this->getGroups();
			return $groups[0];
		}

}