<?php

/**
 * sfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUser');
    }
    
    public function retrieveUserList(Doctrine_Query $q)
    {      
      $root_alias = $q->getRootAlias();
      $q->leftJoin($root_alias.'.Profile p');
      $q->leftJoin($root_alias.'.Groups g');            
      return $q;		
    }

    public function retrieveAnyByUsername($username)
    {
      $query = Doctrine_Core::getTable('sfGuardUser')->createQuery('u')
        ->where('u.username = ?', $username);
        //->addWhere('u.is_active = ?', $isActive);
      return $query->fetchOne();
    }        

    public function orderByUserFirstName(Doctrine_Query $q, $direction = 'asc')
    {
      return $q->orderBy('p.first_name '.$direction);
    }
    
    public function orderByUserLastName(Doctrine_Query $q, $direction = 'asc')
    {
      return $q->orderBy('p.last_name '.$direction);
    }
    
    
}