generator:
  class:                          sfDoctrineMagicGenerator
  param:
    model_class:                  News
    theme:                        infosoft3
    non_verbose_templates:        true
    with_show:                    false
    singular:                     ~
    plural:                       ~
    route_prefix:                 news
    with_doctrine_route:          true
    actions_base_class:           sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display:           [slug, updated_at]
        title:                    Новости
      filter:  ~
      form:
        display: [slug, categories_list, name, title, description, keywords, text]
      edit:
        title:                    Редактирование новости
      new:
        title:                    Добавление новости