<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeIndex('order_item', 'order_item', array(
             'fields' => 
             array(
              0 => 'order_id',
              1 => 'item_id',
             ),
             'type' => 'unique',
             ));
    }

    public function down()
    {
        $this->addIndex('order_item', 'order_item', array(
             'fields' => 
             array(
              0 => 'order_id',
              1 => 'item_id',
             ),
             'type' => 'unique',
             ));
    }
}