<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('spd', 'details', 'string', '5000', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('spd', 'details');
    }
}