<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version8 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('spd', 'spd_name', 'string', '500', array(
             'notnull' => '1',
             ));
        $this->addColumn('spd', 'spd_name_genitive', 'string', '500', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('spd', 'spd_name');
        $this->removeColumn('spd', 'spd_name_genitive');
    }
}