<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('order', 'order_spd_id_spd_id', array(
             'name' => 'order_spd_id_spd_id',
             'local' => 'spd_id',
             'foreign' => 'id',
             'foreignTable' => 'spd',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));
        $this->addIndex('order', 'order_spd_id', array(
             'fields' => 
             array(
              0 => 'spd_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('order', 'order_spd_id_spd_id');
        $this->removeIndex('order', 'order_spd_id', array(
             'fields' => 
             array(
              0 => 'spd_id',
             ),
             ));
    }
}