<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropTable('payment');
        $this->addColumn('order', 'deleted_at', 'timestamp', '25', array(
             'notnull' => '',
             ));
        $this->addColumn('order_item', 'deleted_at', 'timestamp', '25', array(
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->createTable('payment', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'order_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'amount_uah' => 
             array(
              'type' => 'double',
              'length' => '',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->removeColumn('order', 'deleted_at');
        $this->removeColumn('order_item', 'deleted_at');
    }
}