<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('spd', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->addColumn('item', 'doc_name', 'string', '255', array(
             'notnull' => '1',
             ));
        $this->addColumn('item_unit_type', 'doc_name', 'string', '255', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->dropTable('spd');
        $this->removeColumn('item', 'doc_name');
        $this->removeColumn('item_unit_type', 'doc_name');
    }
}