<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('order', 'spd_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('order', 'spd_id');
    }
}