<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('item', 'item_main_image_id_item_image_id');
        $this->createForeignKey('item', 'item_main_image_id_item_image_id_1', array(
             'name' => 'item_main_image_id_item_image_id_1',
             'local' => 'main_image_id',
             'foreign' => 'id',
             'foreignTable' => 'item_image',
             'onUpdate' => '',
             'onDelete' => 'SET NULL',
             ));
        $this->addIndex('item', 'item_main_image_id', array(
             'fields' => 
             array(
              0 => 'main_image_id',
             ),
             ));
    }

    public function down()
    {
        $this->createForeignKey('item', 'item_main_image_id_item_image_id', array(
             'name' => 'item_main_image_id_item_image_id',
             'local' => 'main_image_id',
             'foreign' => 'id',
             'foreignTable' => 'item_image',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->dropForeignKey('item', 'item_main_image_id_item_image_id_1');
        $this->removeIndex('item', 'item_main_image_id', array(
             'fields' => 
             array(
              0 => 'main_image_id',
             ),
             ));
    }
}