<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version11 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('item', 'commission_percent', 'double', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('item', 'commission_percent');
    }
}