<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version15 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('order', 'order_order_owner_id_order_owner_id', array(
             'name' => 'order_order_owner_id_order_owner_id',
             'local' => 'order_owner_id',
             'foreign' => 'id',
             'foreignTable' => 'order_owner',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));
        $this->createForeignKey('order_item', 'order_item_status_id_order_item_status_id', array(
             'name' => 'order_item_status_id_order_item_status_id',
             'local' => 'status_id',
             'foreign' => 'id',
             'foreignTable' => 'order_item_status',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));
        $this->addIndex('order', 'order_order_owner_id', array(
             'fields' => 
             array(
              0 => 'order_owner_id',
             ),
             ));
        $this->addIndex('order_item', 'order_item_status_id', array(
             'fields' => 
             array(
              0 => 'status_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('order', 'order_order_owner_id_order_owner_id');
        $this->dropForeignKey('order_item', 'order_item_status_id_order_item_status_id');
        $this->removeIndex('order', 'order_order_owner_id', array(
             'fields' => 
             array(
              0 => 'order_owner_id',
             ),
             ));
        $this->removeIndex('order_item', 'order_item_status_id', array(
             'fields' => 
             array(
              0 => 'status_id',
             ),
             ));
    }
}