<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version18 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('order', 'order_user_id_sf_guard_user_id');
        $this->removeColumn('order', 'user_id');
        $this->changeColumn('order', 'order_owner_id', 'integer', '8', array(
             'notnull' => '1',
             'default' => '1',
             ));
        $this->changeColumn('order_item', 'status_id', 'integer', '8', array(
             'notnull' => '1',
             'default' => '1',
             ));
    }

    public function down()
    {
        $this->addColumn('order', 'user_id', 'integer', '8', array(
             ));
        $this->createForeignKey('order', 'order_user_id_sf_guard_user_id', array(
             'name' => 'order_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'SET NULL',
             ));
    }
}