<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version23 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('client', 'org_name', 'string', '255', array(
             'notnull' => '1',
             'default' => '',
             ));
    }

    public function down()
    {

    }
}