<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version24 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('category_translation', 'item_contacts', 'string', '2000', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('category_translation', 'item_contacts');
    }
}