<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version25 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('item_translation', 'passenger_insurance', 'string', '10000', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('item_translation', 'passenger_insurance');
    }
}