<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version27 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('order', 'order_pier_id_pier_id', array(
             'name' => 'order_pier_id_pier_id',
             'local' => 'pier_id',
             'foreign' => 'id',
             'foreignTable' => 'pier',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));
        $this->addIndex('order', 'order_pier_id', array(
             'fields' => 
             array(
              0 => 'pier_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('order', 'order_pier_id_pier_id');
        $this->removeIndex('order', 'order_pier_id', array(
             'fields' => 
             array(
              0 => 'pier_id',
             ),
             ));
    }
}