<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version32 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('client_contact', 'client_id', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->addColumn('client_contact', 'contact_status_id', 'integer', '8', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('client_contact', 'client_id');
        $this->removeColumn('client_contact', 'contact_status_id');
    }
}