<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version38 extends Doctrine_Migration_Base
{
    public function up()
    {
        //$this->dropForeignKey('client_contact', 'client_contact_created_by_sf_guard_user_profile_id');
    }

    public function down()
    {
		/*
        $this->createForeignKey('client_contact', 'client_contact_created_by_sf_guard_user_profile_id', array(
             'name' => 'client_contact_created_by_sf_guard_user_profile_id',
             'local' => 'created_by',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user_profile',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));*/
    }
}