<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version37 extends Doctrine_Migration_Base
{
    public function up()
    {
		/*
        $this->createForeignKey('client_contact', 'client_contact_created_by_sf_guard_user_profile_id', array(
             'name' => 'client_contact_created_by_sf_guard_user_profile_id',
             'local' => 'created_by',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user_profile',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));*/
			 /*
        $this->addIndex('client_contact', 'client_contact_created_by', array(
             'fields' => 
             array(
              0 => 'created_by',
             ),
             ));*/
    }

    public function down()
    {/*
        $this->dropForeignKey('client_contact', 'client_contact_created_by_sf_guard_user_profile_id');*/
		/*
        $this->removeIndex('client_contact', 'client_contact_created_by', array(
             'fields' => 
             array(
              0 => 'created_by',
             ),
             ));*/
    }
}