<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version41 extends Doctrine_Migration_Base
{
    public function up()
    {
        //$this->dropForeignKey('client_contact', 'client_contact_client_id_order_id');
		//$this->dropForeignKey('client_contact', 'client_contact_client_id_client_id');
		
        $this->createForeignKey('client_contact', 'client_contact_order_id_order_id', array(
             'name' => 'client_contact_order_id_order_id',
             'local' => 'order_id',
             'foreign' => 'id',
             'foreignTable' => 'order',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));
			 
        $this->addIndex('client_contact', 'client_contact_order_id', array(
             'fields' => 
             array(
              0 => 'order_id',
             ),
             ));
    }

    public function down()
    {
		/*
        $this->createForeignKey('client_contact', 'client_contact_client_id_order_id', array(
             'name' => 'client_contact_client_id_order_id',
             'local' => 'client_id',
             'foreign' => 'id',
             'foreignTable' => 'order',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));*/
        $this->dropForeignKey('client_contact', 'client_contact_order_id_order_id');
        $this->removeIndex('client_contact', 'client_contact_order_id', array(
             'fields' => 
             array(
              0 => 'order_id',
             ),
             ));
    }
}