<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version40 extends Doctrine_Migration_Base
{
    public function up()
    {
		/*
        $this->dropForeignKey('client_contact', 'client_contact_client_id_client_id');
        $this->createForeignKey('client_contact', 'client_contact_client_id_order_id', array(
             'name' => 'client_contact_client_id_order_id',
             'local' => 'client_id',
             'foreign' => 'id',
             'foreignTable' => 'order',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));
        $this->addIndex('client_contact', 'client_contact_client_id', array(
             'fields' => 
             array(
              0 => 'client_id',
             ),
             ));*/
    }

    public function down()
    {
		/*
        $this->createForeignKey('client_contact', 'client_contact_client_id_client_id', array(
             'name' => 'client_contact_client_id_client_id',
             'local' => 'client_id',
             'foreign' => 'id',
             'foreignTable' => 'client',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));
        $this->dropForeignKey('client_contact', 'client_contact_client_id_order_id');
        $this->removeIndex('client_contact', 'client_contact_client_id', array(
             'fields' => 
             array(
              0 => 'client_id',
             ),
             ));*/
    }
}