<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version39 extends Doctrine_Migration_Base
{
    public function up()
    {
		$this->dropForeignKey('client_contact', 'client_contact_client_id_client_id');
        $this->removeColumn('client_contact', 'client_id');
        $this->addColumn('client_contact', 'order_id', 'integer', '8', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->addColumn('client_contact', 'client_id', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->removeColumn('client_contact', 'order_id');
    }
}