<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version42 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('client_contact', 'contact_time', 'time', '25', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('client_contact', 'contact_time');
    }
}