<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version43 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('pierf', 'name_english', 'string', '255', array(
             ));
        $this->addColumn('pierf', 'link_english', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('pierf', 'name_english');
        $this->removeColumn('pierf', 'link_english');
    }
}