<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version44 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('item_image', 'alt', 'string', '255', array(
             ));
        $this->addColumn('item_image', 'title', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('item_image', 'alt');
        $this->removeColumn('item_image', 'title');
    }
}