<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version45 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('item_temp_image', 'alt', 'string', '255', array(
             'notnull' => '1',
             'default' => '',
             ));
        $this->addColumn('item_temp_image', 'title', 'string', '255', array(
             'notnull' => '1',
             'default' => '',
             ));
        $this->changeColumn('item_image', 'alt', 'string', '255', array(
             'notnull' => '1',
             'default' => '',
             ));
        $this->changeColumn('item_image', 'title', 'string', '255', array(
             'notnull' => '1',
             'default' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('item_temp_image', 'alt');
        $this->removeColumn('item_temp_image', 'title');
    }
}