<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version46 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('item_image', 'alt_en', 'string', '255', array(
             'notnull' => '1',
             'default' => '',
             ));
        $this->addColumn('item_image', 'title_en', 'string', '255', array(
             'notnull' => '1',
             'default' => '',
             ));
        $this->addColumn('item_temp_image', 'alt_en', 'string', '255', array(
             'notnull' => '1',
             'default' => '',
             ));
        $this->addColumn('item_temp_image', 'title_en', 'string', '255', array(
             'notnull' => '1',
             'default' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('item_image', 'alt_en');
        $this->removeColumn('item_image', 'title_en');
        $this->removeColumn('item_temp_image', 'alt_en');
        $this->removeColumn('item_temp_image', 'title_en');
    }
}