<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version47 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('item_image', 'width', 'integer', '8', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('item_image', 'height', 'integer', '8', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('item_temp_image', 'width', 'integer', '8', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('item_temp_image', 'height', 'integer', '8', array(
             'notnull' => '1',
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->removeColumn('item_image', 'width');
        $this->removeColumn('item_image', 'height');
        $this->removeColumn('item_temp_image', 'width');
        $this->removeColumn('item_temp_image', 'height');
    }
}