<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version50 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('item', 'html_description');
        $this->addColumn('item_translation', 'html_description', 'string', '1000', array(
             ));
    }

    public function down()
    {
        $this->addColumn('item', 'html_description', 'string', '1000', array(
             ));
        $this->removeColumn('item_translation', 'html_description');
    }
}