<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version52 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('item_translation', 'title', 'string', '255', array(
             ));
        $this->changeColumn('item_translation', 'h1', 'string', '255', array(
             ));
    }

    public function down()
    {

    }
}