<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version53 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('category_translation', 'seo_short_text', 'string', '2000', array(
             ));
        $this->addColumn('category_translation', 'seo_full_text', 'string', '2000', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('category_translation', 'seo_short_text');
        $this->removeColumn('category_translation', 'seo_full_text');
    }
}