<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version54 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('item_translation', 'listing_text', 'string', '1000', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('item_translation', 'listing_text');
    }
}