<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version58 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('category_advertisement', 'category_advertisement_category_id_category_id', array(
             'name' => 'category_advertisement_category_id_category_id',
             'local' => 'category_id',
             'foreign' => 'id',
             'foreignTable' => 'category',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('category_advertisement', 'category_advertisement_advertisement_id_advertisement_id', array(
             'name' => 'category_advertisement_advertisement_id_advertisement_id',
             'local' => 'advertisement_id',
             'foreign' => 'id',
             'foreignTable' => 'advertisement',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('advertisement_translation', 'advertisement_translation_id_advertisement_id', array(
             'name' => 'advertisement_translation_id_advertisement_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'advertisement',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('category_advertisement', 'category_advertisement_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
        $this->addIndex('category_advertisement', 'category_advertisement_advertisement_id', array(
             'fields' => 
             array(
              0 => 'advertisement_id',
             ),
             ));
        $this->addIndex('advertisement_translation', 'advertisement_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('category_advertisement', 'category_advertisement_category_id_category_id');
        $this->dropForeignKey('category_advertisement', 'category_advertisement_advertisement_id_advertisement_id');
        $this->dropForeignKey('advertisement_translation', 'advertisement_translation_id_advertisement_id');
        $this->removeIndex('category_advertisement', 'category_advertisement_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
        $this->removeIndex('category_advertisement', 'category_advertisement_advertisement_id', array(
             'fields' => 
             array(
              0 => 'advertisement_id',
             ),
             ));
        $this->removeIndex('advertisement_translation', 'advertisement_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}