<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version59 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('item', 'hide_attractions', 'boolean', '25', array(
             'default' => '0',
             ));
        $this->addColumn('item_translation', 'html_keywords', 'string', '1000', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('item', 'hide_attractions');
        $this->removeColumn('item_translation', 'html_keywords');
    }
}