<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version63 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('kitchen_translation', 'kitchen_translation_id_kitchen_id', array(
             'name' => 'kitchen_translation_id_kitchen_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'kitchen',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('kitchen_translation', 'kitchen_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('kitchen_translation', 'kitchen_translation_id_kitchen_id');
        $this->removeIndex('kitchen_translation', 'kitchen_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}