<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version64 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('item_translation', 'main_image_title', 'string', '1000', array(
             ));
        $this->addColumn('item_translation', 'main_image_alt', 'string', '1000', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('item_translation', 'main_image_title');
        $this->removeColumn('item_translation', 'main_image_alt');
    }
}