all:
  metas:
    title: Отчеты | Киевская судоходная компания &laquo;Рентфлот&raquo;
    robots: noindex, nofollow
  stylesheets: [-*, backend/common.css, backend/screen.css, backend/reports.css]
  layout:     layout_backend
  
motorShipBillsSuccess:  
  stylesheets:    
    - /magicLibsPlugin/jquery/jquery-ui/infosoft3/jquery-ui-1.8.7.custom.css
    - /magicLibsPlugin/grid/infosoft3/css/grid.css

  javascripts:
    - /magicLibsPlugin/jquery/jquery-ui/jquery-ui-1.8.7.magic.js
    - /magicLibsPlugin/jquery/jquery-ui/jquery-ui-i18n.js
    - /magicLibsPlugin/jquery/plugins/jquery.hoverIntent.minified.js
    - /magicLibsPlugin/grid/infosoft3/js/grid-i18n.js
    - main.js  
    
billsSuccess:  
  stylesheets:    
    - /magicLibsPlugin/jquery/jquery-ui/infosoft3/jquery-ui-1.8.7.custom.css
    - /magicLibsPlugin/grid/infosoft3/css/grid.css

  javascripts:
    - /magicLibsPlugin/jquery/jquery-ui/jquery-ui-1.8.7.magic.js
    - /magicLibsPlugin/jquery/jquery-ui/jquery-ui-i18n.js
    - /magicLibsPlugin/jquery/plugins/jquery.hoverIntent.minified.js
    - /magicLibsPlugin/grid/infosoft3/js/grid-i18n.js
    - main.js      
    
    
categoriesSuccess:  
  stylesheets:    
    - /magicLibsPlugin/jquery/jquery-ui/infosoft3/jquery-ui-1.8.7.custom.css
    - /magicLibsPlugin/grid/infosoft3/css/grid.css

  javascripts:
    - /magicLibsPlugin/jquery/jquery-ui/jquery-ui-1.8.7.magic.js
    - /magicLibsPlugin/jquery/jquery-ui/jquery-ui-i18n.js
    - /magicLibsPlugin/jquery/plugins/jquery.hoverIntent.minified.js
    - /magicLibsPlugin/grid/infosoft3/js/grid-i18n.js
    - main.js          